# labeler "simple" schema
# Comment is applied to both issues and pull requests.
# If you need a more robust solution, consider the "full" schema.
comment: |
  👍 Thanks for this!
  🏷 I have applied any labels matching special text in your issue.

# Labels is an object where:
# - keys are labels
# - values are array of string patterns to match against title + body in issues/prs
labels:
  "🌏 live":
    - '/\blive\b/i'
  "🛠 refactoring":
    - '/\brefactoring\b/i'
  "🧪 test-code":
    - '/\btest code\b/i'
