# comment: |
#   🏷 I have applied any labels matching special text in your title and description.

# labels:
#   "🌏 live":
#     - '\blive release\b'
#   "🛠 refactoring":
#     - '\bRefactoring\b'


":pencil2: docs":
- "**/*.md"

":test_tube: test-code":
- "spec/**/*.spec.php"
- "spec/**/*.spec.js"

":package: app:package":
- package.json
- package-lock.json
- composer.json