name: Pull Request Labeler
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize


jobs:
  labeler:
    runs-on: ubuntu-latest
    steps:
      - name: Check Labels
        id: labeler
        uses: actions/labeler@v4
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"

